image: jamesdbloom/docker-java8-maven

stages:
    - test
    - install
    
maven-test:
    stage: test
    script:
        - mvn test

maven-install:
    stage: install
    script:
        - mvn clean install
    artifacts:
        paths:
            - target/*.jar